# Trying intersection of callers (FAILED)

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os.path
import seaborn as sns
import math
import re
import gzip

/home/spellegrini/miniconda3/envs/clustering_3d/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
input_mut_profile = "/workspace/projects/clustering_3d/evaluation/datasets/datasets_ch/input/mut_profile"
input_maf = "/workspace/projects/clustering_3d/evaluation/datasets/datasets_ch/input/maf"
pd.read_csv(f"{input_maf}/OTHER_WXS_TCGA_FULL.in.maf", sep="\t")

/tmp/jobs/spellegrini/8892130/ipykernel_1283/1484548907.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(f"{input_maf}/OTHER_WXS_TCGA_FULL.in.maf", sep="\t")

,Hugo_Symbol,Chromosome,Start_Position,End_Position,Reference_Allele,Tumor_Seq_Allele2,Tumor_Sample_Barcode,Variant_Classification,Transcript_ID,HGVSp_Short
0,SAMD11,1,861377,861377,G,A,TCGA-X2-A95T,Missense_Mutation,ENST00000342066,p.R19Q
1,SAMD11,1,865589,865589,C,A,TCGA-EW-A1PH,Missense_Mutation,ENST00000342066,p.L43M
2,SAMD11,1,866453,866453,C,A,TCGA-EW-A6SD,synonymous_variant,ENST00000342066,.
3,SAMD11,1,871146,871146,C,A,TCGA-FD-A6TD,splice_region_variant,ENST00000342066,.
4,SAMD11,1,874447,874447,G,A,TCGA-BF-A1Q0,Missense_Mutation,ENST00000342066,p.R153H
...,...,...,...,...,...,...,...,...,...,...
401917,TMLHE,X,154754142,154754142,C,T,TCGA-QN-A5NN,synonymous_variant,ENST00000334398,.
401918,TMLHE,X,154754220,154754220,G,T,TCGA-SX-A71V,stop_gained,ENST00000334398,.
401919,TMLHE,X,154774805,154774805,C,A,TCGA-E7-A4XJ,Missense_Mutation,ENST00000334398,p.A45S
401920,TMLHE,X,154774839,154774839,G,T,TCGA-CV-7414,Missense_Mutation,ENST00000334398,p.S33R
401921,TMLHE,X,154774895,154774895,C,A,TCGA-CH-5748,Missense_Mutation,ENST00000334398,p.D15Y

In [3]:
cols_maf = ["Hugo_Symbol", "Chromosome", "Reference_Allele", 
            "Tumor_Seq_Allele2", "Tumor_Sample_Barcode",	"Variant_Classification", "Transcript_ID", "HGVSp_Short"]

In [4]:
all_ch_mut = pd.read_csv("/workspace/projects/boostdm_ch/output/run_20220127/discovery/mutations.tsv", sep="\t")
all_ch_mut["aachange"] = "p." + all_ch_mut["aachange"]
all_ch_mut = all_ch_mut.rename(columns={"gene" : "Hugo_Symbol",
                                       "chr" : "Chromosome", 
                                       "ref_cod" : "Reference_Allele", 
                                       "mut_cod" : "Tumor_Seq_Allele2", 
                                       "impact" : "Variant_Classification",
                                       "sampleID" : "Tumor_Sample_Barcode",
                                       "pid" : "Transcript_ID",
                                        "aachange" : "HGVSp_Short"})
all_ch_mut = all_ch_mut[cols_maf + ["COHORT"]]
all_ch_mut

,Hugo_Symbol,Chromosome,Reference_Allele,Tumor_Seq_Allele2,Tumor_Sample_Barcode,Variant_Classification,Transcript_ID,HGVSp_Short,COHORT
0,COL16A1,1,C,A,CPCT02010349T_CPCT02010349R,Synonymous,ENSP00000362776,p.P761P,OTHER_WGS_HMF_MUTECT
1,NRP1,10,G,A,CPCT02010349T_CPCT02010349R,Missense,ENSP00000265371,p.E784K,OTHER_WGS_HMF_MUTECT
2,NCR3LG1,11,C,A,CPCT02010349T_CPCT02010349R,Missense,ENSP00000341637,p.H85N,OTHER_WGS_HMF_MUTECT
3,NAV3,12,G,A,CPCT02010349T_CPCT02010349R,Essential_Splice,ENSP00000381007,p..,OTHER_WGS_HMF_MUTECT
4,FAM83G,17,C,A,CPCT02010349T_CPCT02010349R,Synonymous,ENSP00000373647,p.S116S,OTHER_WGS_HMF_MUTECT
...,...,...,...,...,...,...,...,...,...
667415,CDCA2,8,G,C,TCGA-ZX-AA5X,Missense,ENSP00000328228,p.K627N,OTHER_WXS_TCGA_FULL
667416,MROH1,8,C,T,TCGA-ZX-AA5X,Missense,ENSP00000435565,p.A64V,OTHER_WXS_TCGA_FULL
667417,C9orf78,9,C,T,TCGA-ZX-AA5X,Synonymous,ENSP00000361524,p.I180I,OTHER_WXS_TCGA_FULL
667418,NOTCH1,9,G,A,TCGA-ZX-AA5X,Missense,ENSP00000277541,p.A1944T,OTHER_WXS_TCGA_FULL
667419,DDX53,X,C,T,TCGA-ZX-AA5X,Missense,ENSP00000368667,p.R624C,OTHER_WXS_TCGA_FULL

In [5]:
all_ch_mut["Prot_pos"] = all_ch_mut.apply(lambda x: re.sub(r'\D+', "", x["HGVSp_Short"]), axis=1)
all_ch_mut

,Hugo_Symbol,Chromosome,Reference_Allele,Tumor_Seq_Allele2,Tumor_Sample_Barcode,Variant_Classification,Transcript_ID,HGVSp_Short,COHORT,Prot_pos
0,COL16A1,1,C,A,CPCT02010349T_CPCT02010349R,Synonymous,ENSP00000362776,p.P761P,OTHER_WGS_HMF_MUTECT,761
1,NRP1,10,G,A,CPCT02010349T_CPCT02010349R,Missense,ENSP00000265371,p.E784K,OTHER_WGS_HMF_MUTECT,784
2,NCR3LG1,11,C,A,CPCT02010349T_CPCT02010349R,Missense,ENSP00000341637,p.H85N,OTHER_WGS_HMF_MUTECT,85
3,NAV3,12,G,A,CPCT02010349T_CPCT02010349R,Essential_Splice,ENSP00000381007,p..,OTHER_WGS_HMF_MUTECT,
4,FAM83G,17,C,A,CPCT02010349T_CPCT02010349R,Synonymous,ENSP00000373647,p.S116S,OTHER_WGS_HMF_MUTECT,116
...,...,...,...,...,...,...,...,...,...,...
667415,CDCA2,8,G,C,TCGA-ZX-AA5X,Missense,ENSP00000328228,p.K627N,OTHER_WXS_TCGA_FULL,627
667416,MROH1,8,C,T,TCGA-ZX-AA5X,Missense,ENSP00000435565,p.A64V,OTHER_WXS_TCGA_FULL,64
667417,C9orf78,9,C,T,TCGA-ZX-AA5X,Synonymous,ENSP00000361524,p.I180I,OTHER_WXS_TCGA_FULL,180
667418,NOTCH1,9,G,A,TCGA-ZX-AA5X,Missense,ENSP00000277541,p.A1944T,OTHER_WXS_TCGA_FULL,1944
667419,DDX53,X,C,T,TCGA-ZX-AA5X,Missense,ENSP00000368667,p.R624C,OTHER_WXS_TCGA_FULL,624

In [6]:
wgs_df = all_ch_mut[all_ch_mut["COHORT"].str.startswith("OTHER_WGS_HMF")]
wgs_df

,Hugo_Symbol,Chromosome,Reference_Allele,Tumor_Seq_Allele2,Tumor_Sample_Barcode,Variant_Classification,Transcript_ID,HGVSp_Short,COHORT,Prot_pos
0,COL16A1,1,C,A,CPCT02010349T_CPCT02010349R,Synonymous,ENSP00000362776,p.P761P,OTHER_WGS_HMF_MUTECT,761
1,NRP1,10,G,A,CPCT02010349T_CPCT02010349R,Missense,ENSP00000265371,p.E784K,OTHER_WGS_HMF_MUTECT,784
2,NCR3LG1,11,C,A,CPCT02010349T_CPCT02010349R,Missense,ENSP00000341637,p.H85N,OTHER_WGS_HMF_MUTECT,85
3,NAV3,12,G,A,CPCT02010349T_CPCT02010349R,Essential_Splice,ENSP00000381007,p..,OTHER_WGS_HMF_MUTECT,
4,FAM83G,17,C,A,CPCT02010349T_CPCT02010349R,Synonymous,ENSP00000373647,p.S116S,OTHER_WGS_HMF_MUTECT,116
...,...,...,...,...,...,...,...,...,...,...
51626,RAB44,6,A,G,WIDE01010464T_WIDE01010464R,Synonymous,ENSP00000481054,p.T553T,OTHER_WGS_HMF_MOSAIC,553
51627,POR,7,C,G,WIDE01010464T_WIDE01010464R,Missense,ENSP00000419970,p.L405V,OTHER_WGS_HMF_MOSAIC,405
51628,SLC16A2,X,C,T,WIDE01010464T_WIDE01010464R,Nonsense,ENSP00000465734,p.R314*,OTHER_WGS_HMF_MOSAIC,314
51629,UBE4B,1,G,A,WIDE01010481T_WIDE01010481R,Missense,ENSP00000343001,p.R717Q,OTHER_WGS_HMF_MOSAIC,717
51630,PPM1D,17,C,T,WIDE01010481T_WIDE01010481R,Nonsense,ENSP00000306682,p.R572*,OTHER_WGS_HMF_MOSAIC,572

In [7]:
wgs_df["Caller"] = wgs_df.COHORT.apply(lambda x: x.split("OTHER_WGS_HMF_")[-1])
wgs_df_mutect = wgs_df[wgs_df["Caller"] == "MUTECT"].drop(
    columns=["Caller", "COHORT", "Transcript_ID", "Chromosome", "Reference_Allele", "Tumor_Seq_Allele2"]).reset_index(drop=True)
wgs_df_mosaic = wgs_df[wgs_df["Caller"] == "MOSAIC"].drop(
    columns=["Caller", "COHORT", "Transcript_ID", "Chromosome", "Reference_Allele", "Tumor_Seq_Allele2"]).reset_index(drop=True)
wgs_df_full = wgs_df[wgs_df["Caller"] == "FULL"].drop(
    columns=["Caller", "COHORT", "Transcript_ID", "Chromosome", "Reference_Allele", "Tumor_Seq_Allele2"]).reset_index(drop=True)

wgs_df["Caller"] = wgs_df.COHORT.apply(lambda x: x.split("OTHER_WGS_HMF_")[-1])
wgs_df_mutect = wgs_df[wgs_df["Caller"] == "MUTECT"].drop(
    columns=["Caller", "COHORT", "Transcript_ID", "Chromosome", "Reference_Allele", "Tumor_Seq_Allele2"]).reset_index(drop=True)
wgs_df_mosaic = wgs_df[wgs_df["Caller"] == "MOSAIC"].drop(
    columns=["Caller", "COHORT", "Transcript_ID", "Chromosome", "Reference_Allele", "Tumor_Seq_Allele2"]).reset_index(drop=True)
wgs_df_full = wgs_df[wgs_df["Caller"] == "FULL"].drop(
    columns=["Caller", "COHORT", "Transcript_ID", "Chromosome", "Reference_Allele", "Tumor_Seq_Allele2"]).reset_index(drop=True)

wgs_pos_mosaic = wgs_df_mosaic.apply(lambda x: f'{x["Hugo_Symbol"]}-{x["Prot_pos"]}', axis=1).reset_index(drop=True)
wgs_pos_mutect = wgs_df_mutect.apply(lambda x: f'{x["Hugo_Symbol"]}-{x["Prot_pos"]}', axis=1).reset_index(drop=True)
wgs_pos_full = wgs_df_full.apply(lambda x: f'{x["Hugo_Symbol"]}-{x["Prot_pos"]}', axis=1).reset_index(drop=True)
wgs_intersect_df = wgs_df_mosaic[wgs_pos_mosaic.isin(wgs_pos_mutect) & wgs_pos_mosaic.isin(wgs_pos_full)]
wgs_intersect_df

/tmp/jobs/spellegrini/8892130/ipykernel_1283/1515262322.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wgs_df["Caller"] = wgs_df.COHORT.apply(lambda x: x.split("OTHER_WGS_HMF_")[-1])
/tmp/jobs/spellegrini/8892130/ipykernel_1283/1515262322.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wgs_df["Caller"] = wgs_df.COHORT.apply(lambda x: x.split("OTHER_WGS_HMF_")[-1])

,Hugo_Symbol,Tumor_Sample_Barcode,Variant_Classification,HGVSp_Short,Prot_pos
1,COL16A1,CPCT02010349T_CPCT02010349R,Synonymous,p.P761P,761
2,NRP1,CPCT02010349T_CPCT02010349R,Missense,p.E784K,784
3,NCR3LG1,CPCT02010349T_CPCT02010349R,Missense,p.H85N,85
6,FAM83G,CPCT02010349T_CPCT02010349R,Synonymous,p.S116S,116
15,SLCO2A1,CPCT02010349T_CPCT02010349R,Synonymous,p.R314R,314
...,...,...,...,...,...
11416,ANKRD60,WIDE01010464T_WIDE01010464R,Synonymous,p.R310R,310
11417,CXCL14,WIDE01010464T_WIDE01010464R,Missense,p.C37R,37
11421,SLC16A2,WIDE01010464T_WIDE01010464R,Nonsense,p.R314*,314
11422,UBE4B,WIDE01010481T_WIDE01010481R,Missense,p.R717Q,717
11423,PPM1D,WIDE01010481T_WIDE01010481R,Nonsense,p.R572*,572

In [219]:
wgs_intersect_df[wgs_intersect_df["Variant_Classification"] == "Missense"].groupby("Hugo_Symbol").count().iloc[:, 0].sort_values(ascending=False)[:50]

Hugo_Symbol
DNMT3A      46
TTN         15
ATM          6
COL6A3       5
CSMD1        5
MYH8         4
EYS          4
SLC3A1       4
SF3B1        4
FAT1         4
MTA2         4
FBN2         4
DNAH9        4
NOS1         4
ADGRV1       4
PDZRN3       3
APOB         3
SETD1B       3
DNAH6        3
TET2         3
DNAH5        3
NEB          3
ADAMTSL1     3
APC          3
RP1          3
NFASC        3
DOCK8        3
CXorf67      3
MUC16        3
CCDC168      3
USH2A        3
MUC5B        3
PLXNA4       3
TP53         3
PTPRK        3
TP63         3
ABCC11       3
KLHDC7A      3
RYR3         3
DSCAML1      3
SVEP1        3
PABPC5       2
TRIO         2
LAMA1        2
DNAH10       2
PTPRT        2
TPH1         2
DNAH7        2
KRT85        2
TPP2         2
Name: Tumor_Sample_Barcode, dtype: int64

In [118]:
wxs_df = all_ch_mut[all_ch_mut["COHORT"].str.startswith("OTHER_WXS_TCGA")]
wxs_df

,Hugo_Symbol,Chromosome,Reference_Allele,Tumor_Seq_Allele2,Tumor_Sample_Barcode,Variant_Classification,Transcript_ID,HGVSp_Short,COHORT,Prot_pos
51631,PADI6,1,G,T,TCGA-02-0003,Missense,ENSP00000483125,p.K498N,OTHER_WXS_TCGA_MOSAIC,498
51632,C4BPB,1,C,A,TCGA-02-0003,Missense,ENSP00000243611,p.P142T,OTHER_WXS_TCGA_MOSAIC,142
51633,NLRC5,16,C,T,TCGA-02-0003,Synonymous,ENSP00000262510,p.C1403C,OTHER_WXS_TCGA_MOSAIC,1403
51634,COL3A1,2,C,T,TCGA-02-0003,Synonymous,ENSP00000304408,p.C1268C,OTHER_WXS_TCGA_MOSAIC,1268
51635,TNIK,3,C,A,TCGA-02-0003,Synonymous,ENSP00000399511,p.T1351T,OTHER_WXS_TCGA_MOSAIC,1351
...,...,...,...,...,...,...,...,...,...,...
667415,CDCA2,8,G,C,TCGA-ZX-AA5X,Missense,ENSP00000328228,p.K627N,OTHER_WXS_TCGA_FULL,627
667416,MROH1,8,C,T,TCGA-ZX-AA5X,Missense,ENSP00000435565,p.A64V,OTHER_WXS_TCGA_FULL,64
667417,C9orf78,9,C,T,TCGA-ZX-AA5X,Synonymous,ENSP00000361524,p.I180I,OTHER_WXS_TCGA_FULL,180
667418,NOTCH1,9,G,A,TCGA-ZX-AA5X,Missense,ENSP00000277541,p.A1944T,OTHER_WXS_TCGA_FULL,1944
667419,DDX53,X,C,T,TCGA-ZX-AA5X,Missense,ENSP00000368667,p.R624C,OTHER_WXS_TCGA_FULL,624

In [208]:
wxs_df["Caller"] = wxs_df.COHORT.apply(lambda x: x.split("OTHER_WXS_TCGA_")[-1])
wxs_df_mosaic = wxs_df[wxs_df["Caller"] == "MOSAIC"].drop(
    columns=["Caller", "COHORT", "Transcript_ID", "Chromosome", "Reference_Allele", "Tumor_Seq_Allele2"]).reset_index(drop=True)
wxs_df_full = wxs_df[wxs_df["Caller"] == "FULL"].drop(
    columns=["Caller", "COHORT", "Transcript_ID", "Chromosome", "Reference_Allele", "Tumor_Seq_Allele2"]).reset_index(drop=True)

wxs_pos_mosaic = wxs_df_mosaic.apply(lambda x: f'{x["Hugo_Symbol"]}-{x["Prot_pos"]}', axis=1).reset_index(drop=True)
wxs_pos_full = wxs_df_full.apply(lambda x: f'{x["Hugo_Symbol"]}-{x["Prot_pos"]}', axis=1).reset_index(drop=True)
wxs_ix_intersect = wxs_pos_mosaic.isin(wxs_pos_full)
wxs_df_intersect = wxs_df_mosaic[wxs_ix_intersect]
wxs_df_intersect

/tmp/jobs/spellegrini/8869446/ipykernel_51029/432867690.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wxs_df["Caller"] = wxs_df.COHORT.apply(lambda x: x.split("OTHER_WXS_TCGA_")[-1])

,Hugo_Symbol,Tumor_Sample_Barcode,Variant_Classification,HGVSp_Short,Prot_pos
0,PADI6,TCGA-02-0003,Missense,p.K498N,498
1,C4BPB,TCGA-02-0003,Missense,p.P142T,142
2,NLRC5,TCGA-02-0003,Synonymous,p.C1403C,1403
3,COL3A1,TCGA-02-0003,Synonymous,p.C1268C,1268
4,TNIK,TCGA-02-0003,Synonymous,p.T1351T,1351
...,...,...,...,...,...
223603,FLNC,TCGA-ZX-AA5X,Synonymous,p.G1343G,1343
223604,FASTK,TCGA-ZX-AA5X,Missense,p.P298S,298
223605,MROH1,TCGA-ZX-AA5X,Missense,p.A64V,64
223606,C9orf78,TCGA-ZX-AA5X,Synonymous,p.I180I,180
223607,DDX53,TCGA-ZX-AA5X,Missense,p.R624C,624

# Mouse

### Convert .txt simple format into .vcf

In [15]:
def sort_vcf(vcf_file):
    """
    Sort the vcf file from by chromosomes and position.
    """
    
    df = pd.DataFrame(vcf_file)

    # Define the custom sort order for Chromosome
    chromosome_order = {'1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, '10': 10,
                        '11': 11, '12': 12, '13': 13, '14': 14, '15': 15, '16': 16, '17': 17, '18': 18, '19': 19,
                        '20': 20, '21': 21, 'X': 22, 'Y': 23, 'M': 24}

    # Convert 'Chromosome' column to a temporary categorical column for sorting
    df['#CHROM'] = df['#CHROM'].astype(str)
    df['Chromosome_sort'] = df['#CHROM'].map(chromosome_order)
    # Sort and drop temporary col
    sorted_df = df.sort_values(by=['Chromosome_sort', 'POS'], ignore_index=True)
    sorted_df.drop('Chromosome_sort', axis=1, inplace=True)

    return sorted_df.reset_index(drop=True)

In [4]:
mouse_path = "/workspace/projects/clustering_3d/evaluation/datasets/datasets_mouse/input/raw_data" 
path = f"{mouse_path}/Liver_DEN_strelka_July2017_mm10.txt"
mouse_df = pd.read_csv(path, sep="\t")

/tmp/jobs/spellegrini/8869446/ipykernel_15677/696072087.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  mouse_df = pd.read_csv(path, sep="\t")

In [8]:
mouse_df = mouse_df[["CHROMOSOME", "POSITION", "SAMPLE", "REF", "ALT"]]
mouse_df = mouse_df.rename(columns={"CHROMOSOME" : "#CHROM",
                                    "POSITION" : "POS",
                                    "SAMPLE" : "ID"})
mouse_df["QUAL"] = "."
mouse_df["FILTER"] = "PASS"
mouse_df["INFO"] = "."

In [17]:
%%time
mouse_df = sort_vcf(mouse_df)
mouse_df

CPU times: user 39.7 s, sys: 11.1 s, total: 50.8 s
Wall time: 50.8 s

         #CHROM      POS               ID REF ALT QUAL FILTER INFO
0             1  3000671  do9806_93131_N1   A   G    .   PASS    .
1             1  3000832  do9414_91603_N1   T   C    .   PASS    .
2             1  3000943  do9786_91932_N7   T   C    .   PASS    .
3             1  3000976  do9219_90886_N4   A   T    .   PASS    .
4             1  3001034  do9429_91618_N2   G   A    .   PASS    .
...         ...      ...              ...  ..  ..  ...    ...  ...
22921896      M     3682  do9171_90022_N2   C   T    .   PASS    .
22921897      M     8218  do9744_92188_N6   C   T    .   PASS    .
22921898      M    13756  do9212_90810_N5   C   T    .   PASS    .
22921899      M    14328  do9822_93244_N3   G   A    .   PASS    .
22921900      M    14372  do9809_93131_N5   G   A    .   PASS    .

[22921901 rows x 8 columns]

In [24]:
mouse_df["#CHROM"].unique()

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', 'X', 'Y', 'M'],
      dtype=object)

In [20]:
# %%time
# mouse_df.to_csv(f"{mouse_path}/liver_strelka.vcf", sep="\t", index=False)

CPU times: user 1min 6s, sys: 1.71 s, total: 1min 8s
Wall time: 1min 8s

### Load VEP output
* Run VEP using vep_and_parse_mouse.sh in build/preprocessing/

#### Reload it and check if I can run it with vep_input for O3D (all transcripts should be there)

In [2]:
import pandas as pd
path = "/workspace/projects/clustering_3d/o3d_analysys/datasets/input/cancer_mouse/raw_data/liver_strelka_mm39/Liver_DEN_strelka_July2017_mm10.txt"
liver_df = pd.read_table(path)
liver_df

/tmp/jobs/spellegrini/10373218/ipykernel_682040/3485451430.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  liver_df = pd.read_table(path)

         CHROMOSOME  POSITION REF ALT            SAMPLE  TYPE CANCER_TYPE
0                10   3145729   A   G   do9714_91620_N3  subs       Liver
1                10   3145729   A   T   do9714_91620_N3  subs       Liver
2                10   3145729   A   G   do9786_91932_N7  subs       Liver
3                10   3145729   A   T   do9786_91932_N7  subs       Liver
4                10   3278912   T   C   do9386_90793_N2  subs       Liver
...             ...       ...  ..  ..               ...   ...         ...
22921896          3   4767854   A   T   do9442_91837_N5  subs       Liver
22921897          Y  90793815   T   A  do12459_91948_N4  subs       Liver
22921898          Y  90793868   C   T   do9172_90170_N2  subs       Liver
22921899          Y  90794273   C   G   do9201_90802_N1  subs       Liver
22921900          Y  90805575   T   A   do9197_90797_N2  subs       Liver

[22921901 rows x 7 columns]

In [61]:
out_vep = pd.read_csv(f"{mouse_path}/backup/liver_strelka.maf", sep='\t')
out_vep

,Hugo_Symbol,Tumor_Sample_Barcode,Variant_Classification,Transcript_ID,HGVSp_Short
0,4933401J01Rik,do9710_91945_N1,upstream_gene_variant,ENSMUST00000193812,NaN
1,4933401J01Rik,do9848_93260_N7,upstream_gene_variant,ENSMUST00000193812,NaN
2,4933401J01Rik,do9811_93131_N8,upstream_gene_variant,ENSMUST00000193812,NaN
3,4933401J01Rik,do9181_90447_N3,upstream_gene_variant,ENSMUST00000193812,NaN
4,4933401J01Rik,do9698_90447_N3,upstream_gene_variant,ENSMUST00000193812,NaN
...,...,...,...,...,...
11858509,Mid1-ps1,do9449_91839_N1,"intron_variant,non_coding_transcript_variant",ENSMUST00000167967,NaN
11858510,Gm47283,do12459_91948_N4,"intron_variant,non_coding_transcript_variant",ENSMUST00000179483,NaN
11858511,Gm47283,do9172_90170_N2,"intron_variant,non_coding_transcript_variant",ENSMUST00000179483,NaN
11858512,Gm47283,do9201_90802_N1,"intron_variant,non_coding_transcript_variant",ENSMUST00000179483,NaN
11858513,Gm47283,do9197_90797_N2,"intron_variant,non_coding_transcript_variant",ENSMUST00000179483,NaN

In [63]:
out_vep[out_vep["Hugo_Symbol"] == "Braf"].Transcript_ID.unique()

array(['ENSMUST00000002487'], dtype=object)

#### End

In [7]:
out_vep = pd.read_csv(f"{mouse_path}/backup/liver_strelka.maf", sep='\t')
out_vep = out_vep[out_vep["Variant_Classification"] == "missense_variant"].reset_index(drop=True)
out_vep

,Hugo_Symbol,Tumor_Sample_Barcode,Variant_Classification,Transcript_ID,HGVSp_Short
0,Xkr4,do9866_94316_N3,missense_variant,ENSMUST00000070533,p.E639V
1,Xkr4,do9819_93243_N2,missense_variant,ENSMUST00000070533,p.I587V
2,Xkr4,do9213_90880_N1,missense_variant,ENSMUST00000070533,p.T575A
3,Xkr4,do9442_91837_N5,missense_variant,ENSMUST00000070533,p.E562G
4,Xkr4,do9766_93092_N7,missense_variant,ENSMUST00000070533,p.D526Y
...,...,...,...,...,...
175108,4933400A11Rik,do9714_91620_N3,missense_variant,ENSMUST00000068874,p.H34L
175109,Mid1,do9236_91097_N1,missense_variant,ENSMUST00000112105,p.T149I
175110,Mid1,do9464_91932_N1,missense_variant,ENSMUST00000112105,p.D324G
175111,Mid1,do9877_91942_N3,missense_variant,ENSMUST00000112105,p.L349P
175112,Mid1,do9836_93258_N10,missense_variant,ENSMUST00000112105,p.Y555C

In [8]:
import os
uniprot_ids = os.listdir("/workspace/projects/clustering_3d/clustering_3d/datasets_mouse/pdb_structures")
uniprot_ids = [uni_id.split("-")[1] for uni_id in list(set(uniprot_ids)) if uni_id.endswith(".pdb")]
len(uniprot_ids)

21615

In [9]:
import time
import requests
import gzip
import io

def get_response_jobid(response):
    """
    Get jobId after submitting ID Mapping job to UniprotKB. 
    """
    
    try:
        data = response.json()
        job_id = data.get("jobId")
    except:
        job_id = None
        
    return job_id


def get_mapping_jobid(uniprot_ids):
    """
    Submit an ID Mapping job to UniprotKB.
    """
    
    command = f"https://rest.uniprot.org/idmapping/run?from=UniProtKB_AC-ID&to=UniProtKB&ids={','.join(uniprot_ids)}"
    response = requests.post(command)
    job_id = get_response_jobid(response)
    
    i = 60
    while job_id is None:
        time.sleep(1) 
        job_id = get_response_jobid(response)
        if i % 60 == 0:
            print(f"Requesting ID mapping job to UniprotKB for IDs.. [waited {i-59}s]")
        i += 1
    
    return job_id


def load_df_from_url(url):
    """
    Load a pandas dataframe from url.
    """

    try:
        response = requests.get(url)
        decompressed_data = gzip.decompress(response.content)
        df = pd.read_csv(io.BytesIO(decompressed_data), sep='\t')
    except:
        df = None
    
    return df


def split_lst_into_chunks(lst, chunk_size = 5000):
    """
    Simple split a list into list of list of chunk_size elements.
    """
    
    return [lst[i:i+chunk_size] for i in range(0, len(lst), chunk_size)]


def uniprot_to_hudo_df(uniprot_ids):
    """
    Given a list of Uniprot IDs (from any species), request an Id 
    mapping job to UniprotKB to retrieve the corresponding Hugo 
    symbols and additional protein info. Return a pandas dataframe.
    It is recommended to provide batches of IDs up to 5000 elements.
    """
    
    job_id = get_mapping_jobid(uniprot_ids)
    url = f"https://rest.uniprot.org/idmapping/uniprotkb/results/stream/{job_id}?compressed=true&fields=accession%2Cid%2Cprotein_name%2Cgene_names%2Corganism_name%2Clength&format=tsv"
    df = load_df_from_url(url)
    
    i = 60
    while df is None:
        time.sleep(1)
        df = load_df_from_url(url)
        if i % 60 == 0:
            print(f"Waiting for UniprotKB mapping job to produce url.. [waited {i-59}s]")
        i =+ 1 
        
    return df


def convert_dict_hugo_to_uniprot(dict_uniprot_hugo):
    """
    Convert a Uniprot IDs to Hugo symbol dictionary to a Hugo symbo to 
    Uniprot IDs dictionary, if multiple Hugo symbols are mapped to the 
    same Uniprot ID, add them as multiple keys.
    """
    
    dict_hugo_uniprot = {}

    for uni_id, gene in dict_uniprot_hugo.items():
        if type(gene) == str:
            for g in gene.split(" "):
                dict_hugo_uniprot[g] = uni_id
                
    return dict_hugo_uniprot


def uniprot_to_hugo(uniprot_ids, hugo_as_keys=False):
    """
    Given a list of Uniprot IDs (any species.), request an Id mapping 
    job to UniprotKB to retrieve the corresponding Hugo symbols. 
    Return a dictionary of Uniprot IDs to Hugo symbols or vice versa.
    """
    
    # Split uniprot IDs into chunks
    uniprot_ids_lst = split_lst_into_chunks(uniprot_ids)
    
    # Get a dataframe including all IDs mapping info
    df_lst = []
    for ids in uniprot_ids_lst:
        df = uniprot_to_hudo_df(ids)
        df_lst.append(df)
    df = pd.concat(df_lst)

    # Get a dictionary for Uniprot ID to Hugo symbols
    dictio = {}
    for i,r in df[["Entry", "Gene Names"]].iterrows():
        uni_id, gene = r 
        dictio[uni_id] = gene
    
    # Convert to a dictionary of Hugo symbols to Uniprot IDs
    if hugo_as_keys:
        dictio = convert_dict_hugo_to_uniprot(dictio)
            
    return dictio

In [10]:
%%time
dictio = uniprot_to_hugo(uniprot_ids[:5000], hugo_as_keys=True)

Waiting for UniprotKB mapping job to produce url.. [waited 1s]
CPU times: user 812 ms, sys: 28.1 ms, total: 840 ms
Wall time: 25.2 s

In [11]:
%%time
dictio = uniprot_to_hugo(uniprot_ids[5000:10000], hugo_as_keys=True)

Waiting for UniprotKB mapping job to produce url.. [waited 1s]
CPU times: user 802 ms, sys: 15.5 ms, total: 818 ms
Wall time: 24.5 s

In [12]:
%%time
dictio = uniprot_to_hugo(uniprot_ids[10000:15000], hugo_as_keys=True)

Waiting for UniprotKB mapping job to produce url.. [waited 1s]
CPU times: user 816 ms, sys: 15.7 ms, total: 832 ms
Wall time: 25.3 s

In [13]:
%%time
dictio = uniprot_to_hugo(uniprot_ids[15000:20000], hugo_as_keys=True)

Waiting for UniprotKB mapping job to produce url.. [waited 1s]
CPU times: user 829 ms, sys: 19.9 ms, total: 848 ms
Wall time: 25.6 s

In [14]:
%%time
dictio = uniprot_to_hugo(uniprot_ids[20000:], hugo_as_keys=True)

Waiting for UniprotKB mapping job to produce url.. [waited 1s]
CPU times: user 324 ms, sys: 14.2 ms, total: 338 ms
Wall time: 9.33 s

In [15]:
%%time
dictio = uniprot_to_hugo(uniprot_ids, hugo_as_keys=False)

CPU times: user 1.65 s, sys: 18.3 ms, total: 1.66 s
Wall time: 18.4 s

In [16]:
# Save
import json
output = "/workspace/projects/clustering_3d/clustering_3d/datasets_mouse/af_uniprot_to_gene_id.json"
with open(output, "w") as fp:
    json.dump(dictio, fp)

In [17]:
uniprot_to_gene_dict = dictio
gene_to_uniprot_dict = convert_dict_hugo_to_uniprot(dictio)

### Seq df

In [25]:
import re
import pandas as pd
import numpy as np
import os
import gzip
import io
import csv
import time
import requests
from difflib import SequenceMatcher
from Bio import SeqIO
from Bio.Seq import Seq

In [141]:
import json
import pandas as pd
import json
import argparse
import warnings
from progressbar import progressbar
import requests
import time
import re


# Import from utils


def rounded_up_division(num, den):
    """
    Simply round up the result of the division.
    """
    
    return -(-num // den)


def get_pos_fragments(mut_gene_df):
    """
    Get the corresponding fragment of each position of the protein.
    """
    
    max_f = rounded_up_division(max(mut_gene_df["Pos"]), 1400)
    bins = [n * 1400 for n in range(0, max_f+1)]
    group_names = list(range(1, max_f+1))
    
    return pd.cut(mut_gene_df["Pos"], bins, labels = group_names)


def get_af_id_from_pdb(path_structure):
    """
    Get AlphaFold 2 identifier (UniprotID_F) from path
    """

    return path_structure.split("AF-")[1].split("-model")[0]   


def get_seq_from_pdb(path_structure):
    """
    Get sequense of amino acid residues from PDB structure.
    """
    
    return np.array([record.seq for record in SeqIO.parse(path_structure, 'pdb-seqres')][0])


def get_pdb_path_list_from_dir(path_dir):
    """
    Takes as input a path of a given directory and it 
    outputs a list of paths of the contained PDB files.
    """

    pdb_files = os.listdir(path_dir)
    pdb_path_list = [f"{path_dir}{f}" for f in pdb_files if re.search('.\.pdb$', f) is not None]
    return pdb_path_list


# Backtranslation

def translate_dna(dna_seq):
    """
    Translate dna sequence to protein.
    """
    
    dna_seq = Seq(dna_seq)
    return str(dna_seq.translate()) 


def get_seq_similarity(a, b, decimals=3):
    """
    Compute the similarity ratio between sequences a and b.
    """
    
    return round(SequenceMatcher(a=a, b=b).ratio(), decimals)


## Other functions


def get_seq_df_from_dir(input_path, uniprot_to_gene_dict):
    """
    Parse any PDB structure from a given directory and create 
    a dataframe including HUGO symbol, Uniprot-ID, AF fragment,
    and protein sequence.
    """
    
    # Get all PDB path in directory whose IDs can be mapped to HUGO symbols
    list_prot_path = get_pdb_path_list_from_dir(input_path)[:1000]            ############################################################ SUBSET
    
    list_prot_path = [path for path in list_prot_path if get_af_id_from_pdb(path).split("-F")[0] in uniprot_to_gene_dict.keys()]
    pdb_not_mapped = set([get_af_id_from_pdb(path).split("-F")[0] for path in list_prot_path if get_af_id_from_pdb(path).split("-F")[0] not in uniprot_to_gene_dict.keys()])
    if len(pdb_not_mapped) > 0:                                 
        warnings.warn(f"WARNING........... {len(pdb_not_mapped)} Uniprot-ID not found in the Uniprot-HUGO mapping dictionary")

    # Get Uniprot ID, HUGO, F and protein sequence of any PDB in dir
    gene_lst = []
    uni_id_lst = []
    f_lst = []
    seq_lst = []

    for path_structure in progressbar(list_prot_path):
        uniprot_id, f = get_af_id_from_pdb(path_structure).split("-F")
        gene = uniprot_to_gene_dict[uniprot_id]
        seq = "".join(list(get_seq_from_pdb(path_structure)))
        gene_lst.append(gene)
        uni_id_lst.append(uniprot_id)
        f_lst.append(f)
        seq_lst.append(seq)

    seq_df = pd.DataFrame({"Gene" : gene_lst, "Uniprot_ID" : uni_id_lst, "F" : f_lst, "Seq" : seq_lst}).sort_values(["Gene", "F"])

    return seq_df


def backtranseq(protein_seqs, organism = "Homo sapiens"):
    """
    Perform backtranslation from proteins to 
    DNA sequences using EMBOS backtranseq.    
    """
    
    # Define the API endpoints
    run_url = "https://www.ebi.ac.uk/Tools/services/rest/emboss_backtranseq/run"
    status_url = "https://www.ebi.ac.uk/Tools/services/rest/emboss_backtranseq/status/"
    result_url = "https://www.ebi.ac.uk/Tools/services/rest/emboss_backtranseq/result/"
    
    # Define the parameters for the API request (an email address must be included)
    params = {"email": "emaple.email@irbbarcelona.org",
              "sequence": protein_seqs,
              "outseqformat": "plain",
              "molecule": "dna",
              "organism": organism}
    
    # Submit the job request and retrieve the job ID
    response = requests.post(run_url, data=params)
    job_id = response.text.strip()

    # Wait for the job to complete
    status = ""
    while status != "FINISHED":
        time.sleep(10)
        result = requests.get(status_url + job_id)
        status = result.text.strip()

    # Retrieve the results of the job
    result = requests.get(result_url + job_id + "/out")
    dna_seq = result.text.strip()
    
    return dna_seq


def batch_backtranseq(df, batch_size, organism = "Homo sapiens"):
    """
    Given a dataframe including protein sequences, it divides the 
    sequences into batches of a given size and run EMBOSS backtranseq 
    (https://www.ebi.ac.uk/Tools/st/emboss_backtranseq/) to translate 
    them into DNA sequences.
    """
    
    batches = df.groupby(df.index // batch_size)
    lst_batches = []
        
    # Iterate over batches
    for _, batch in progressbar(batches):

        # Get input format for backtranseq 
        batch_seq = "\n".join(batch.reset_index(drop=True).apply(lambda x: f'>\n{x["Seq"]}', axis=1).values)

        # Run backtranseq
        batch_dna = backtranseq(batch_seq, organism=organism)

        # Parse output
        batch_dna = re.split(">EMBOSS_\d+", batch_dna.replace("\n", ""))[1:]

        batch["Seq_dna"] = batch_dna
        lst_batches.append(batch)
        
    return pd.concat(lst_batches)

In [142]:
input = "/workspace/projects/clustering_3d/clustering_3d/datasets_mouse/pdb_structures/"
seq_df = get_seq_df_from_dir(input, uniprot_to_gene_dict)

100% (991 of 991) |######################| Elapsed Time: 0:00:01 Time:  0:00:01

In [135]:
seq_df

,Gene,Uniprot_ID,F,Seq
886,1700014B07Rik,A0A5F8MPC3,1,METAPAFPRAALPGPRLRAAGPARLTGRQQSPLRPRPPPSWRGRTA...
218,1700017N19Rik,A0A087WPJ1,1,MAEVGNDCYFFVNSTCIKGSQCRFRHCEEALGSDTVCSLWRERKCL...
602,1700018G05Rik,A0A1B0GSI2,1,MIVMHLVGHPQLTGTEGVATAHTKENSSRGPRETREPAPCTRSWRS...
223,1700019A02Rik,A0A087WPV9,1,MVGSSWCLHPHGGLLEIIEMNDKLRNRQEIVNGLNIFLEENEEEAY...
203,1700025B11Rik,A0A087WNZ6,1,MSTKNEEQNEDQSESVVIPHIQDHHCLAILAFCFFFPLGYLAYRSS...
...,...,...,...,...
628,Zscan4-ps2,A0A1C7CYU6,1,MASQQAPAKDLQTNNLEFTPTDSSGVQWAEDISNSPSAQLNFSPSN...
568,Zscan4-ps3,A0A1B0GRH6,1,MASQQAPAKDLQTNNLEFTPTDSSGVQWAEDISNSPSAQLNFSPSN...
565,Zscan4e,A0A1B0GRE8,1,MASQQAPAKDLQTNNLEFTPTDSSGVQWAEDISNSPSAQLNFSPSN...
754,NaN,A0A286YDM5,1,MEVRNVTEFVLLGLTSNPRSQVLLFILFLVIYLLTLAGNLLMLLLI...
888,NaN,A0A5F8MPE6,1,MEKSSNTTGSGGPKSDSQLPEKLRRTFSARAAKIKARKANRETSAA...

In [143]:
# Annotate df with DNA sequences
print("Performing back translation")
seq_df = batch_backtranseq(seq_df, 500, organism = "Mus musculus")
seq_df

  0% (0 of 2) |                          | Elapsed Time: 0:00:00 ETA:  --:--:--

Performing back translation

100% (2 of 2) |##########################| Elapsed Time: 0:00:50 Time:  0:00:50

,Gene,Uniprot_ID,F,Seq,Seq_dna
218,1700017N19Rik,A0A087WPJ1,1,MAEVGNDCYFFVNSTCIKGSQCRFRHCEEALGSDTVCSLWRERKCL...,ATGGCCGAGGTGGGCAACGACTGCTACTTCTTCGTGAACAGCACCT...
223,1700019A02Rik,A0A087WPV9,1,MVGSSWCLHPHGGLLEIIEMNDKLRNRQEIVNGLNIFLEENEEEAY...,ATGGTGGGCAGCAGCTGGTGCCTGCACCCCCACGGCGGCCTGCTGG...
203,1700025B11Rik,A0A087WNZ6,1,MSTKNEEQNEDQSESVVIPHIQDHHCLAILAFCFFFPLGYLAYRSS...,ATGAGCACCAAGAACGAGGAGCAGAACGAGGACCAGAGCGAGAGCG...
288,2210017I01Rik,A0A0A6YVV1,1,MSSQQHQQKCKLSANCPPKCPQQGPQVPTSCLPLSAPPAPACCVST...,ATGAGCAGCCAGCAGCACCAGCAGAAGTGCAAGCTGAGCGCCAACT...
296,2310009B15Rik,A0A0A6YWI4,1,MAAQGIWTLARVSLGRPPPRAEGFRQQLNSTLGSTSEGARGGSAAD...,ATGGCCGCCCAGGGCATCTGGACCCTGGCCAGGGTGAGCCTGGGCA...
...,...,...,...,...,...
628,Zscan4-ps2,A0A1C7CYU6,1,MASQQAPAKDLQTNNLEFTPTDSSGVQWAEDISNSPSAQLNFSPSN...,ATGGCCAGCCAGCAGGCCCCCGCCAAGGACCTGCAGACCAACAACC...
568,Zscan4-ps3,A0A1B0GRH6,1,MASQQAPAKDLQTNNLEFTPTDSSGVQWAEDISNSPSAQLNFSPSN...,ATGGCCAGCCAGCAGGCCCCCGCCAAGGACCTGCAGACCAACAACC...
565,Zscan4e,A0A1B0GRE8,1,MASQQAPAKDLQTNNLEFTPTDSSGVQWAEDISNSPSAQLNFSPSN...,ATGGCCAGCCAGCAGGCCCCCGCCAAGGACCTGCAGACCAACAACC...
754,NaN,A0A286YDM5,1,MEVRNVTEFVLLGLTSNPRSQVLLFILFLVIYLLTLAGNLLMLLLI...,ATGGAGGTGAGGAACGTGACCGAGTTCGTGCTGCTGGGCCTGACCA...
888,NaN,A0A5F8MPE6,1,MEKSSNTTGSGGPKSDSQLPEKLRRTFSARAAKIKARKANRETSAA...,ATGGAGAAGAGCAGCAACACCACCGGCAGCGGCGGCCCCAAGAGCG...

In [148]:
def add_extra_genes_to_seq_df(seq_df, uniprot_to_gene_dict):
    """
    If multiple genes are mapping to a given Uniprot_ID, add 
    each gene name with corresponding sequence info to the seq_df.
    """
    
    lst_extra_genes = []

    for _, seq_row in seq_df.iterrows():

        uni_id = seq_row["Uniprot_ID"]
        gene_id = uniprot_to_gene_dict[uni_id]
        if pd.isnull(gene_id) == False:

            gene_id = gene_id.split(" ")
            if len(gene_id) > 1:

                for gene in gene_id:
                    if gene != seq_row["Gene"]:
                        lst_extra_genes.append((gene, seq_row["Uniprot_ID"], seq_row["F"], seq_row["Seq"], seq_row["Seq_dna"]))

    seq_df_extra_genes = pd.DataFrame(lst_extra_genes, columns=["Gene", "Uniprot_ID", "F", "Seq", "Seq_dna"])
    
    return pd.concat((seq_df, seq_df_extra_genes)).reset_index(drop=True)

In [145]:
seq_df_extra = add_extra_genes_to_seq_df(seq_df, uniprot_to_gene_dict)
seq_df_extra

,Gene,Uniprot_ID,F,Seq,Seq_dna
0,1700017N19Rik,A0A087WPJ1,1,MAEVGNDCYFFVNSTCIKGSQCRFRHCEEALGSDTVCSLWRERKCL...,ATGGCCGAGGTGGGCAACGACTGCTACTTCTTCGTGAACAGCACCT...
1,1700019A02Rik,A0A087WPV9,1,MVGSSWCLHPHGGLLEIIEMNDKLRNRQEIVNGLNIFLEENEEEAY...,ATGGTGGGCAGCAGCTGGTGCCTGCACCCCCACGGCGGCCTGCTGG...
2,1700025B11Rik,A0A087WNZ6,1,MSTKNEEQNEDQSESVVIPHIQDHHCLAILAFCFFFPLGYLAYRSS...,ATGAGCACCAAGAACGAGGAGCAGAACGAGGACCAGAGCGAGAGCG...
3,2210017I01Rik,A0A0A6YVV1,1,MSSQQHQQKCKLSANCPPKCPQQGPQVPTSCLPLSAPPAPACCVST...,ATGAGCAGCCAGCAGCACCAGCAGAAGTGCAAGCTGAGCGCCAACT...
4,2310009B15Rik,A0A0A6YWI4,1,MAAQGIWTLARVSLGRPPPRAEGFRQQLNSTLGSTSEGARGGSAAD...,ATGGCCGCCCAGGGCATCTGGACCCTGGCCAGGGTGAGCCTGGGCA...
...,...,...,...,...,...
1527,Gm262,A0PK84,1,MLALRLLNVVAPAYFLCISLVTFVLQLFLFLPSMREDPTATPLFSP...,ATGCTGGCCCTGAGGCTGCTGAACGTGGTGGCCCCCGCCTACTTCC...
1528,Znf335,A2A5K6,1,MEENEVESSSDAAPRPGQPEEPSESGLGVCTSEAVSADSSDAATVP...,ATGGAGGAGAACGAGGTGGAGAGCAGCAGCGACGCCGCCCCCAGGC...
1529,Zfp335,A2A5K6,1,MEENEVESSSDAAPRPGQPEEPSESGLGVCTSEAVSADSSDAATVP...,ATGGAGGAGAACGAGGTGGAGAGCAGCAGCGACGCCGCCCCCAGGC...
1530,Znf385c,A2A5E6,1,MLLGPASGSPSPLLASLTLPARPLQPPLDLKHLLAFHLNGTTPLSL...,ATGCTGCTGGGCCCCGCCAGCGGCAGCCCCAGCCCCCTGCTGGCCA...
1531,Zfp385c,A2A5E6,1,MLLGPASGSPSPLLASLTLPARPLQPPLDLKHLLAFHLNGTTPLSL...,ATGCTGCTGGGCCCCGCCAGCGGCAGCCCCAGCCCCCTGCTGGCCA...

In [ ]:
uniprot_to_gene_dict = None
output_seq_df = None

# Load Uniprot ID to HUGO mapping
if uniprot_to_gene_dict is not None:
    uniprot_to_gene_dict = json.load(open(uniprot_to_gene_dict)) 
else:
    uniprot_to_gene_dict = uniprot_to_hugo()  

# Create a dataframe with protein sequences
print("\nGenerating sequence df..")
seq_df = get_seq_df_from_dir(input, uniprot_to_gene_dict)

# Annotate df with DNA sequences
print("Performing back translation")
seq_df = batch_backtranseq(seq_df, 500)
#seq_df.to_csv(output_seq_df, index=False)

sim_ratio = sum(seq_df.apply(lambda x: get_seq_similarity(x.Seq, translate_dna(x.Seq_dna)), axis=1)) / len(seq_df)

## Get mut rate (BBG signature)

### Parse input for bbg signature

In [3]:
import gzip
import pandas as pd

In [4]:
mouse_path = "/workspace/projects/clustering_3d/evaluation/datasets/datasets_mouse/input/raw_data" 
path = f"{mouse_path}/Liver_DEN_strelka_July2017_mm10.txt"
mouse_df_original = pd.read_csv(path, sep="\t")

# Save DataFrame as a compressed TSV file
with gzip.open(f"{mouse_path}/liver_strelka.in.tsv.gz", 'wt') as file:
    mouse_df_original.drop(columns=["TYPE", "CANCER_TYPE"]).to_csv(file, sep='\t', index=False)

/tmp/jobs/spellegrini/8898314/ipykernel_2312/2070478027.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  mouse_df_original = pd.read_csv(path, sep="\t")

### Get regions file from bgreference

In [28]:
import sys

from bgreference import refseq

CHR = [str(i) for i in range(1, 23)] + ['X', 'Y']


def compute_sizes(genome, kmer):
    sizes = []
    for chr_ in CHR:
        seq = refseq(genome, chr_, start=(1 + kmer // 2), size=None)
        sizes.append(tuple(map(str, (chr_, 1 + kmer // 2, len(seq) - kmer // 2))))
    return sizes


def write(sizes):
    print('\t'.join(('CHROMOSOME', 'START', 'END')))
    for s in sizes:
        print('\t'.join(s))


if __name__ == '__main__':
    genome = sys.argv[1]
    kmer = int(sys.argv[2])
    write(compute_sizes(genome, kmer))

### Download WG regions from biomart

Downloaded from

In [17]:
!ls /workspace/projects/clustering_3d/o3d_analysys/datasets/input/cancer_mouse/raw_data/liver_strelka_mm39/

Liver_DEN_strelka_July2017_mm10.txt  mm10ToMm39.over.chain.gz
liftover.py			     mm39_wg_regions.tsv.gz

In [24]:
path_regions = "/workspace/projects/clustering_3d/o3d_analysys/datasets/input/cancer_mouse/raw_data/liver_strelka_mm39/mm39_wg_regions.tsv.gz"
wg_regions = pd.read_csv(path_regions, sep="\t", header=None)
wg_regions.columns = "CHROMOSOME", "SIZE", "INFO"
wg_regions = wg_regions.drop(columns=["INFO"])
wg_regions

                CHROMOSOME       SIZE
0                     chr1  195154279
1                     chr2  181755017
2                     chrX  169476592
3                     chr3  159745316
4                     chr4  156860686
..                     ...        ...
56        chrUn_GL456396v1      21240
57        chrUn_GL456368v1      20208
58                    chrM      16299
59  chr1_MU069434v1_random       8412
60  chr4_JH584295v1_random       1976

[61 rows x 2 columns]

In [ ]:
def sort_regions(regions):
    """
    Sort regions file.
    """
    
    df = regions

    # Define the custom sort order for Chromosome
    chromosome_order = {'1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, '10': 10,
                        '11': 11, '12': 12, '13': 13, '14': 14, '15': 15, '16': 16, '17': 17, '18': 18, '19': 19,
                        '20': 20, '21': 21, 'X': 22, 'Y': 23, 'M': 24}

    # Convert 'Chromosome' column to a temporary categorical column for sorting
    df['CHROMOSOME'] = df['CHROMOSOME'].astype(str)
    df['Chromosome_sort'] = df['CHROMOSOME'].map(chromosome_order)
    # Sort and drop temporary col
    sorted_df = df.sort_values(by=['Chromosome_sort'], ignore_index=True)
    sorted_df.drop('Chromosome_sort', axis=1, inplace=True)

    return sorted_df.reset_index(drop=True)

In [58]:
path_regions = "/workspace/projects/clustering_3d/evaluation/datasets/datasets_mouse/input/raw_data/mm10_wg_regions.tsv"
wg_regions = pd.read_csv(path_regions, sep="\t")

In [43]:
# Depending on pytabix version used, it can be 0-index or 1-index. 

wg_regions["START"] = 2
wg_regions["END"] = wg_regions["size"] - wg_regions["START"]
wg_regions = wg_regions.rename(columns={"#chrom" : "CHROMOSOME"}).drop(columns=["size"])
wg_regions["CHROMOSOME"] = wg_regions["CHROMOSOME"].apply(lambda x: x[3:])

In [26]:
# Se chr1 size = 195471971, Perche non START 1, END 1 + 195471971 ?

195471972

In [52]:
wg_regions = sort_regions(wg_regions)
wg_regions

   CHROMOSOME  START        END
0           1      2  195471969
1           2      2  182113222
2           3      2  160039678
3           4      2  156508114
4           5      2  151834682
5           6      2  149736544
6           7      2  145441457
7           8      2  129401211
8           9      2  124595108
9          10      2  130694991
10         11      2  122082541
11         12      2  120129020
12         13      2  120421637
13         14      2  124902242
14         15      2  104043683
15         16      2   98207766
16         17      2   94987269
17         18      2   90702637
18         19      2   61431564
19          X      2  171031297
20          Y      2   91744696

In [54]:
# out_regions = "/workspace/projects/clustering_3d/evaluation/datasets/datasets_mouse/input/raw_data/mm10_wg.regions.gz"
# wg_regions.to_csv(out_regions, compression='gzip', index=False, sep="\t")

### Run bbgsignature content

In [2]:
import pandas as pd
pd.read_csv("/workspace/projects/clustering_3d/evaluation/datasets/datasets_mouse/input/raw_data/liver_strelka.in.tsv.gz", sep="\t")

/tmp/jobs/spellegrini/8879724/ipykernel_25678/106531960.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv("/workspace/projects/clustering_3d/evaluation/datasets/datasets_mouse/input/raw_data/liver_strelka.in.tsv.gz", sep="\t")

         CHROMOSOME  POSITION REF ALT            SAMPLE
0                10   3145729   A   G   do9714_91620_N3
1                10   3145729   A   T   do9714_91620_N3
2                10   3145729   A   G   do9786_91932_N7
3                10   3145729   A   T   do9786_91932_N7
4                10   3278912   T   C   do9386_90793_N2
...             ...       ...  ..  ..               ...
22921896          3   4767854   A   T   do9442_91837_N5
22921897          Y  90793815   T   A  do12459_91948_N4
22921898          Y  90793868   C   T   do9172_90170_N2
22921899          Y  90794273   C   G   do9201_90802_N1
22921900          Y  90805575   T   A   do9197_90797_N2

[22921901 rows x 5 columns]

In [ ]:
conda env activate bgsignature

In [ ]:
bgsignature count -r /workspace/projects/clustering_3d/evaluation/datasets/datasets_mouse/input/raw_data/mm10_wg.regions.gz -s 3 -g mm10 --exclude-N --collapse -o /workspace/projects/clustering_3d/evaluation/datasets/datasets_mouse/input/mut_profile/wg.counts.gz --cores 4

### Run bbgsignature normalizer

In [ ]:
bgsignature normalize -m /workspace/projects/clustering_3d/evaluation/datasets/datasets_mouse/input/raw_data/liver_strelka.in.tsv.gz -r /workspace/projects/clustering_3d/evaluation/datasets/datasets_mouse/input/raw_data/mm10_wg.regions.gz --normalize /workspace/projects/clustering_3d/evaluation/datasets/datasets_mouse/input/mut_profile/wg.counts.gz -s 3 -g mm10 --collapse --cores 4 -o /workspace/projects/clustering_3d/evaluation/datasets/datasets_mouse/input/mut_profile/liver_strelka.sig.json

In [90]:
import json
mut_profile_192_path = "/workspace/projects/intogen_plus/fixdatasets-20230223/intogen-plus/run_20230224_ALL/intogen_analysis/steps/signature/CBIOP_WGS_PRAD_EURUROL_2017.sig.json"
mut_profile_192 = json.load(open(mut_profile_192_path))

In [95]:
not isinstance(mut_profile_192, dict)

False

### Parse mut profile

In [ ]:
def convert_mut_rate_192_to_96(mut_rate_dict):
    """
    Convert a mut_profile dictionary of 192 items into a list 
    of 96 elements (keep only non-redundant mutations). 
    """
    
    lst_rate = []
    cb  = dict(zip('ACGT', 'TGCA'))
    for ref in ['C', 'T']:
        for alt in cb.keys():
            if ref == alt:
                continue
            else:
                for p in product(cb.keys(), repeat=2):
                    
                    mut = f"{p[0]}{ref}{p[1]}>{alt}"
                    lst_rate.append(mut_rate_dict[mut])
        
    return lst_rate

import json
mut_profile_192_path = "/workspace/projects/intogen_plus/fixdatasets-20230223/intogen-plus/run_20230224_ALL/intogen_analysis/steps/signature/CBIOP_WGS_PRAD_EURUROL_2017.sig.json"
mut_profile_192 = json.load(open(mut_profile_192_path)) 

mut_profile_96 = convert_mut_rate_dict_192_to_vec_96(mut_profile_192)
mut_profile_96_path = "/workspace/projects/clustering_3d/evaluation/datasets/datasets_mouse/input/mut_profile/liver_strelka.mutrate.json"

with open(mut_profile_96_path, 'w') as file:
    json.dump(mut_profile_96, file)

# Debug main

In [58]:
def parse_maf_input(maf_input_path, keep_samples_id=False):
    """
    Parse in.maf file which is used as 
    input for the HotMAPS method.
    """

    # Load
    maf = pd.read_csv(maf_input_path, sep="\t", dtype={'Chromosome': str})

    # Select only missense mutation and extract Gene name and mut
    maf = maf[maf['Variant_Classification'].str.contains('missense_variant')]
    maf["Pos"] = maf.loc[:, "HGVSp_Short"].apply(lambda x: int(re.sub("\\D", "", (x[2:]))))
    maf["WT"] = maf["HGVSp_Short"].apply(lambda x: re.findall("\\D", x[2:])[0])
    maf["Mut"] = maf["HGVSp_Short"].apply(lambda x: re.findall("\\D", x[2:])[1])
    maf = maf[["Hugo_Symbol", "Pos", "WT", "Mut", "Tumor_Sample_Barcode"]]
    maf = maf.sort_values("Pos").rename(columns={"Hugo_Symbol" : "Gene"})

    if keep_samples_id == False:
        maf = maf.drop(columns=["Tumor_Sample_Barcode"])
    
    return maf.reset_index(drop=True)

def parse2_maf_input(maf_input_path, keep_samples_id=False):
    """
    Parse in.maf file which is used as 
    input for the HotMAPS method.
    """

    # Load
    maf = pd.read_csv(maf_input_path, sep="\t", dtype={'Chromosome': str})

    # Select only missense mutation and extract Gene name and mut
    maf = maf[maf['Variant_Classification'].str.contains('missense_variant')]
    maf['Pos'] = maf['HGVSp_Short'].str.extract(r'(\d+)').astype(int)
    maf['WT'] = maf['HGVSp_Short'].str.extract(r'(\D)')[0]
    maf['Mut'] = maf['HGVSp_Short'].str.extract(r'\D(\D)')[0]
    maf = maf[["Hugo_Symbol", "Pos", "WT", "Mut", "Tumor_Sample_Barcode"]]
    maf = maf.sort_values("Pos").rename(columns={"Hugo_Symbol" : "Gene"})

    if keep_samples_id == False:
        maf = maf.drop(columns=["Tumor_Sample_Barcode"])
    
    return maf.reset_index(drop=True)

In [5]:
maf_input_path = "/workspace/projects/clustering_3d/evaluation/datasets/datasets_mouse/input/maf/liver_strelka_parsed.maf"
seq_df_path = "/workspace/projects/clustering_3d/clustering_3d/datasets_mouse/seq_for_mut_prob.csv"
plddt_path = "/workspace/projects/clustering_3d/clustering_3d/datasets_mouse/confidence.csv"

In [6]:
maf = pd.read_csv(maf_input_path, sep="\t")

In [63]:
maf = asd[asd['Variant_Classification'].str.contains('missense_variant')].reset_index(drop=True)

In [ ]:
maf["Pos"] = maf.loc[:, "HGVSp_Short"].apply(lambda x: int(re.sub("\\D", "", (x[2:]))))
maf["WT"] = maf["HGVSp_Short"].apply(lambda x: re.findall("\\D", x[2:])[0])
maf["Mut"] = maf["HGVSp_Short"].apply(lambda x: re.findall("\\D", x[2:])[1])

In [ ]:
maf = maf[["Hugo_Symbol", "Pos", "WT", "Mut", "Tumor_Sample_Barcode"]]
maf = maf.sort_values("Pos").rename(columns={"Hugo_Symbol" : "Gene"})

In [48]:
## Load input and df of DNA sequences

# MAF input
data = parse_maf_input(maf_input_path, keep_samples_id=True)

# Seq df for missense mut prob
seq_df = pd.read_csv(seq_df_path)

# Model confidence
plddt_df = pd.read_csv(plddt_path)


## Run

result_pos_lst = []
result_gene_lst = []

In [59]:
%%time

# MAF input
data = parse2_maf_input(maf_input_path, keep_samples_id=True)
data

CPU times: user 15.5 s, sys: 675 ms, total: 16.2 s
Wall time: 16.2 s

           Gene    Pos WT Mut Tumor_Sample_Barcode
0         Odf2l      2  p   .      do9699_90721_N1
1           Mt4      2  p   .      do9853_94314_N6
2          Ighd      2  p   .      do9735_92187_N2
3          Ghsr      2  p   .      do9712_91599_N1
4       Fam227b      2  p   .      do9159_89986_N1
...         ...    ... ..  ..                  ...
180223      Ttn  33302  p   .      do9711_91416_N2
180224      Ttn  33392  p   .      do9788_93096_N4
180225      Ttn  33400  p   .      do9818_93243_N1
180226      Ttn  33412  p   .      do9395_91217_N3
180227      Ttn  33463  p   .      do9817_93242_N2

[180228 rows x 5 columns]

In [60]:
%%time

# MAF input
data = parse_maf_input(maf_input_path, keep_samples_id=True)
data

CPU times: user 15 s, sys: 632 ms, total: 15.6 s
Wall time: 15.6 s

           Gene    Pos WT Mut Tumor_Sample_Barcode
0         Odf2l      2  E   G      do9699_90721_N1
1           Mt4      2  D   V      do9853_94314_N6
2          Ighd      2  N   K      do9735_92187_N2
3          Ghsr      2  W   R      do9712_91599_N1
4       Fam227b      2  E   K      do9159_89986_N1
...         ...    ... ..  ..                  ...
180223      Ttn  33302  K   M      do9711_91416_N2
180224      Ttn  33392  A   P      do9788_93096_N4
180225      Ttn  33400  T   S      do9818_93243_N1
180226      Ttn  33412  I   V      do9395_91217_N3
180227      Ttn  33463  N   I      do9817_93242_N2

[180228 rows x 5 columns]

In [42]:
## Run

result_pos_lst = []
result_gene_lst = []

# Get genes with enough mut
genes = data.groupby("Gene").apply(lambda x: len(x))
genes_mut = genes[genes >= 2]
genes_no_mut = genes[genes < 2].index
result_gene = pd.DataFrame({"Gene" : genes_no_mut,
                            "Uniprot_ID" : np.nan,
                            "F" : np.nan,
                            "Mut_in_gene" : 1,
                            "Max_mut_pos" : np.nan,
                            "Structure_max_pos" : np.nan,
                            "Status" : "No_mut"})
result_gene_lst.append(result_gene)   

# Get genes with corresponding Uniprot-ID mapping
gene_to_uniprot_dict = {gene : uni_id for gene, uni_id in seq_df[["Gene", "Uniprot_ID"]].drop_duplicates().values}
genes_to_process = [gene for gene in genes_mut.index if gene in gene_to_uniprot_dict.keys()]
seq_df = seq_df[[gene in genes_to_process for gene in seq_df["Gene"]]].reset_index(drop=True)
genes_no_mapping = genes[[gene in genes_mut.index and gene not in gene_to_uniprot_dict.keys() for gene in genes.index]]
result_gene = pd.DataFrame({"Gene" : genes_no_mapping.index,
                            "Uniprot_ID" : np.nan,
                            "F" : np.nan,
                            "Mut_in_gene" : genes_no_mapping.values,
                            "Max_mut_pos" : np.nan,
                            "Structure_max_pos" : np.nan,
                            "Status" : "No_ID_mapping"})

# Mouse analysis

In [67]:
mut = pd.read_table("/workspace/projects/clustering_3d/o3d_analysys/datasets/output/cancer_mouse/run_2024-11-04_13-40-54/liver_strelka/liver_strelka.mutations.processed.tsv")
mut[mut["Gene"] == "Braf"][:60]

,Gene,Pos,WT,Mut,Tumor_Sample_Barcode,Transcript_ID,O3D_transcript_ID,Transcript_status
0,0610009B22Rik,53,M,K,do9706_90887_N2,ENSMUST00000109098,ENSMUST00000007921,Mismatch
1,0610010F05Rik,66,V,A,do9411_91598_N1,ENSMUST00000043356,NaN,O3D_missing
2,0610010F05Rik,179,Y,H,do9736_92187_N3,ENSMUST00000043356,NaN,O3D_missing
3,0610010F05Rik,252,H,Y,do9852_94314_N5,ENSMUST00000043356,NaN,O3D_missing
4,0610010F05Rik,362,I,R,do9245_91113_N2,ENSMUST00000043356,NaN,O3D_missing
...,...,...,...,...,...,...,...,...
180223,ccdc198,21,Q,L,do9450_91839_N2,ENSMUST00000228936,NaN,O3D_missing
180224,ccdc198,210,E,K,do9878_91943_N1,ENSMUST00000228936,NaN,O3D_missing
180225,ccdc198,250,A,V,do9826_93244_N8,ENSMUST00000228936,NaN,O3D_missing
180226,ccdc198,264,D,E,do9435_91604_C1,ENSMUST00000228936,NaN,O3D_missing
180227,ccdc198,284,I,F,do9771_93096_N1,ENSMUST00000228936,NaN,O3D_missing

In [97]:
maf = pd.read_table("/workspace/projects/clustering_3d/o3d_analysys/datasets/input/cancer_mouse/maf/liver_strelka.in.maf")
maf = maf[maf.Hugo_Symbol.isin(["Braf", "Kras"])].reset_index(drop=True)
maf

,Hugo_Symbol,Tumor_Sample_Barcode,Variant_Classification,Transcript_ID,HGVSp_Short
0,Braf,do9457_91930_N1,3_prime_UTR_variant,ENSMUST00000002487,NaN
1,Braf,do9695_90446_N1,3_prime_UTR_variant,ENSMUST00000002487,NaN
2,Braf,do9844_93260_N3,3_prime_UTR_variant,ENSMUST00000002487,NaN
3,Braf,do9408_91539_N3,3_prime_UTR_variant,ENSMUST00000002487,NaN
4,Braf,do9710_91945_N1,3_prime_UTR_variant,ENSMUST00000002487,NaN
...,...,...,...,...,...
1158,Kras,do12479_93100_N6,upstream_gene_variant,ENSMUST00000032399,NaN
1159,Kras,do12474_92188_N3,upstream_gene_variant,ENSMUST00000032399,NaN
1160,Kras,do9838_93258_N12,upstream_gene_variant,ENSMUST00000032399,NaN
1161,Kras,do9823_93244_N4,upstream_gene_variant,ENSMUST00000032399,NaN
1162,Kras,do9875_91932_N4,upstream_gene_variant,ENSMUST00000032399,NaN

In [99]:
maf.to_csv("/workspace/projects/clustering_3d/o3d_analysys/datasets/input/cancer_mouse/maf/liver_strelka.toy.in.maf", index=False, sep="\t")

In [125]:
path = "/workspace/projects/clustering_3d/o3d_analysys/datasets/output/cancer_mouse/run_2024-11-05_20-26-44/liver_strelka.toy"
mut_path = f"{path}/liver_strelka.toy.mutations.processed.tsv"
mut_toy = pd.read_table(mut_path)
mut_toy

,Gene,Pos,WT,Mut,Tumor_Sample_Barcode,Transcript_ID,O3D_transcript_ID,Transcript_status
0,Braf,45,E,G,do9458_91930_N2,ENSMUST00000002487,NaN,O3D_missing
1,Braf,77,H,N,do9170_90022_N1,ENSMUST00000002487,NaN,O3D_missing
2,Braf,127,D,E,do9789_93096_N5,ENSMUST00000002487,NaN,O3D_missing
3,Braf,320,S,L,do9832_93258_N6,ENSMUST00000002487,NaN,O3D_missing
4,Braf,408,L,P,do9433_91620_N2,ENSMUST00000002487,NaN,O3D_missing
...,...,...,...,...,...,...,...,...
179,Kras,61,Q,R,do9428_91618_N1,ENSMUST00000032399,ENSMUST00000111710,Mismatch
180,Kras,61,Q,L,do9428_91618_N1,ENSMUST00000032399,ENSMUST00000111710,Mismatch
181,Kras,61,Q,R,do9799_93129_N2,ENSMUST00000032399,ENSMUST00000111710,Mismatch
182,Kras,61,Q,L,do9799_93129_N2,ENSMUST00000032399,ENSMUST00000111710,Mismatch
183,Kras,76,E,K,do12459_91948_N4,ENSMUST00000032399,ENSMUST00000111710,Mismatch

In [126]:
result_pos_path = f"{path}/liver_strelka.toy.3d_clustering_pos.csv"
result_pos = pd.read_csv(result_pos_path)
result_pos

,Gene,Uniprot_ID,F,Pos,Mut_in_gene,Mut_in_res,Mut_in_vol,Score,Score_obs_sim,pval,...,Rank,Mut_in_cl_vol,Res_in_cl,PAE_vol,pLDDT_res,pLDDT_vol,pLDDT_cl_vol,WT_mismatch,Cancer,Cohort
0,Braf,P28028,1,637,162,155,156,0.924798,83.446518,0.0,...,0,156.0,2.0,0.006410,95.48,95.499860,95.499860,155.0,NaN,liver_strelka.toy
1,Braf,P28028,1,631,162,1,156,0.919119,93.109734,0.0,...,1,156.0,2.0,0.993590,98.58,95.499860,95.499860,1.0,NaN,liver_strelka.toy
2,Braf,P28028,1,408,162,1,1,0.000782,0.085379,1.0,...,2,NaN,NaN,0.000000,32.52,32.520000,NaN,1.0,NaN,liver_strelka.toy
3,Braf,P28028,1,320,162,1,1,0.000672,0.077943,1.0,...,3,NaN,NaN,0.000000,27.59,27.590000,NaN,0.0,NaN,liver_strelka.toy
4,Braf,P28028,1,45,162,1,1,0.000386,0.047099,1.0,...,4,NaN,NaN,0.000000,33.42,33.420000,NaN,0.0,NaN,liver_strelka.toy
5,Braf,P28028,1,127,162,1,1,0.000317,0.040383,1.0,...,5,NaN,NaN,0.000000,35.79,35.790000,NaN,0.0,NaN,liver_strelka.toy
6,Braf,P28028,1,77,162,1,1,0.000139,0.018465,1.0,...,6,NaN,NaN,0.000000,89.04,89.040000,NaN,0.0,NaN,liver_strelka.toy
7,Braf,P28028,1,469,162,1,1,0.000005,0.000745,1.0,...,7,NaN,NaN,0.000000,88.95,88.950000,NaN,1.0,NaN,liver_strelka.toy
8,Kras,P32883,1,12,22,10,20,0.796174,6.901697,0.0,...,0,20.0,4.0,2.350000,94.74,91.009995,91.009995,NaN,NaN,liver_strelka.toy
9,Kras,P32883,1,13,22,1,20,0.794881,8.045598,0.0,...,1,20.0,4.0,2.350000,94.73,91.009995,91.009995,NaN,NaN,liver_strelka.toy
10,Kras,P32883,1,61,22,7,17,0.631085,7.039743,0.0,...,2,20.0,4.0,4.117647,83.37,90.058235,91.009995,NaN,NaN,liver_strelka.toy
11,Kras,P32883,1,14,22,2,13,0.310494,3.733244,0.0,...,3,20.0,4.0,0.846154,97.24,95.123850,91.009995,NaN,NaN,liver_strelka.toy
12,Kras,P32883,1,24,22,1,1,0.001837,0.023565,1.0,...,4,NaN,NaN,0.000000,95.77,95.770000,NaN,NaN,NaN,liver_strelka.toy
13,Kras,P32883,1,76,22,1,1,0.001736,0.023607,1.0,...,5,NaN,NaN,0.000000,97.92,97.920000,NaN,NaN,NaN,liver_strelka.toy

In [127]:
result_gene_path = f"{path}/liver_strelka.toy.3d_clustering_genes.csv"
result_gene = pd.read_csv(result_gene_path)
result_gene

,Gene,Ens_Gene_ID,Uniprot_ID,pval,qval,C_gene,C_pos,C_label,Score_obs_sim_top_vol,Clust_res,...,Ratio_not_in_structure,Ratio_WT_mismatch,Mut_zero_mut_prob,Pos_zero_mut_prob,Cancer,Cohort,Transcript_ID,O3D_transcript_ID,Transcript_status,Status
0,Braf,NaN,P28028,0.0,0.0,1,[637 631],[0. 0.],93.109734,2,...,0,0.975309,0,NaN,NaN,liver_strelka.toy,ENSMUST00000002487,NaN,O3D_missing,Processed
1,Kras,ENSMUSG00000030265,P32883,0.0,0.0,1,[12 13 61 14],[0. 0. 0. 0.],8.045598,4,...,0,0.000000,0,NaN,NaN,liver_strelka.toy,ENSMUST00000032399,ENSMUST00000111710,Mismatch,Processed

### End cazzeggio

In [2]:
import pandas as pd

In [29]:
mouse_pos_result = pd.read_csv("/workspace/projects/clustering_3d/o3d_analysys/datasets/output/cancer_mouse/run_2024-11-04_13-40-54/liver_strelka/liver_strelka.3d_clustering_pos.csv")
mouse_gene_result = pd.read_csv("/workspace/projects/clustering_3d/o3d_analysys/datasets/output/cancer_mouse/run_2024-11-04_13-40-54/liver_strelka/liver_strelka.3d_clustering_genes.csv")

In [8]:
mouse_pos_result = pd.read_csv("/workspace/projects/clustering_3d/evaluation/tool_output/run_20230608_mouse/Liver_strelka_2017.3d_clustering_pos.csv")
mouse_gene_result = pd.read_csv("/workspace/projects/clustering_3d/evaluation/tool_output/run_20230608_mouse/Liver_strelka_2017.3d_clustering_genes.csv")

In [18]:
mouse_gene_result[:60].drop(columns=['Uniprot_ID', "pval", 'pLDDT_top_vol', 'pLDDT_top_comm_vol', 'Status', 'Cancer', 'Cohort', "Tot_samples", "Samples_in_top_vol", "Samples_in_top_comm_vol", "Clust_res"])

,Gene,qval,C_gene,C_pos,C_community,Ratio_obs_sim_top_vol,Mut_in_gene,Clust_mut,Mut_in_top_vol,Mut_in_top_comm_vol
0,Hras,0.00000,1,[61 12 13],[0. 0. 0.],inf,350,341.0,341.0,341.0
1,Braf,0.00000,1,[637 631],[0. 0.],90.675025,162,156.0,156.0,156.0
2,H2-M5,0.00000,1,[347],[0.],65.432984,157,151.0,151.0,151.0
3,Nrcam,0.00000,1,[714 676 716 688],[0. 0. 0. 0.],56.050080,125,99.0,99.0,99.0
4,Ncl,0.00000,1,[107],[0.],34.644913,66,61.0,61.0,61.0
5,Itga9,0.00000,1,[179],[0.],27.512761,109,70.0,70.0,70.0
6,Nkx2-5,0.00000,1,[273],[0.],21.778911,50,42.0,42.0,42.0
7,Olfr1242,0.00000,1,[ 36 279 73],[0. 0. 0.],17.554267,40,38.0,38.0,38.0
8,Egfr,0.00000,1,[254],[0.],16.310410,47,34.0,34.0,34.0
9,Gm5134,0.00000,1,[635],[0.],16.281568,70,44.0,44.0,44.0
10,Oaf,0.00000,1,[133],[0.],14.697380,37,35.0,35.0,35.0
11,Rdh10,0.00000,1,[136 133],[0. 0.],12.687365,32,28.0,28.0,28.0
12,9530002B09Rik,0.00000,1,[5],[0.],12.566828,35,31.0,31.0,31.0
13,Chd5,0.00000,1,[1888],[0.],11.923891,72,28.0,28.0,28.0
14,Fam126b,0.00000,1,[490],[0.],11.314176,27,22.0,22.0,22.0
15,Zfp184,0.00000,1,[168],[0.],9.380280,22,17.0,17.0,17.0
16,Pbp2,0.00000,1,[123 122 17],[0. 0. 0.],7.941862,26,23.0,23.0,23.0
17,Kras,0.00000,1,[12 13 61 14],[0. 0. 0. 0.],7.673587,22,20.0,20.0,20.0
18,Olfr945,0.00000,1,[92],[0.],7.395317,34,23.0,23.0,23.0
19,Ccdc9,0.00000,1,[224],[0.],6.702145,11,10.0,10.0,10.0
20,Gm20721,0.00000,1,[22],[0.],6.456593,19,13.0,13.0,13.0
21,Rap1gap,0.00000,1,[405],[0.],6.312924,21,14.0,14.0,14.0
22,Mylk,0.00000,1,[1641],[0.],6.294105,32,13.0,13.0,13.0
23,Unk,0.00000,1,[591],[0.],6.164195,22,12.0,12.0,12.0
24,Tdrd6,0.00000,1,[298],[0.],6.009603,72,16.0,16.0,16.0
25,Mab21l4,0.00000,1,[130],[0.],5.838393,26,16.0,16.0,16.0
26,Zmynd10,0.00000,1,[192],[0.],5.249385,17,13.0,13.0,13.0
27,Plcl1,0.00000,1,[663],[0.],4.347430,39,14.0,14.0,14.0
28,Vmn2r74,0.00000,1,[51 94],[0. 0.],4.032435,39,12.0,12.0,12.0
29,St8sia3,0.00000,1,[113],[0.],3.630678,22,12.0,12.0,12.0
30,Soat2,0.00000,1,[84],[0.],3.527611,22,10.0,10.0,10.0
31,Ebf3,0.00000,1,[556],[0.],3.492045,30,10.0,10.0,10.0
32,Saxo1,0.00000,1,[232 230],[0. 0.],3.418260,23,8.0,8.0,8.0
33,Evpl,0.00000,1,[457],[0.],3.397278,46,10.0,10.0,10.0
34,Tnc,0.00000,1,[62],[0.],3.210614,61,9.0,9.0,9.0
35,Txk,0.00000,1,[106 103 109],[0. 0. 0.],3.132542,26,10.0,10.0,10.0
36,Tepsin,0.00000,1,[362 321 361],[0. 0. 0.],3.097745,9,6.0,6.0,6.0
37,Angel2,0.00000,1,[97],[0.],3.076529,8,6.0,6.0,6.0
38,Ankrd63,0.00000,1,[ 86 114 88],[0. 0. 0.],3.064409,7,6.0,6.0,6.0
39,Bpifb5,0.00000,1,[18],[0.],2.982920,23,10.0,10.0,10.0
40,Rps25,0.00000,1,[118],[0.],2.905756,8,7.0,7.0,7.0
41,Nol6,0.00000,1,[207],[0.],2.746241,41,10.0,10.0,10.0
42,Lrfn5,0.00000,1,[512 429],[0. 0.],2.713499,19,7.0,7.0,7.0
43,Ifi47,0.00000,1,[45 44],[0. 0.],2.695163,6,5.0,5.0,5.0
44,Npas1,0.00000,1,[351 383],[0. 0.],2.666975,12,6.0,6.0,6.0
45,Pdxdc1,0.00000,1,[162 163 324],[0. 0. 0.],2.665633,11,6.0,6.0,6.0
46,Ccdc178,0.00000,1,[739 736],[0. 0.],2.661947,29,7.0,7.0,7.0
47,Krt77,0.00000,1,[251 257 249],[0. 0. 0.],2.655064,16,6.0,6.0,6.0
48,Dot1l,0.00000,1,[994],[0.],2.637831,17,5.0,5.0,5.0
49,Sh2d3c,0.00000,1,[47],[0.],2.624367,16,6.0,6.0,6.0
50,Vmn2r22,0.00000,1,[653 730 668 712 714 707 708 758 718 674 663],[0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.],2.624205,34,22.0,9.0,9.0
51,Ccdc54,0.00000,1,[41 36 44],[0. 0. 0.],2.618848,13,6.0,6.0,6.0
52,Adamtsl3,0.00000,1,[1380 1335],[0. 0.],2.523232,54,9.0,9.0,9.0
53,Pum1,0.00000,1,[ 996 1013 992],[0. 0. 0.],2.488469,18,6.0,6.0,6.0
54,Ccdc33,0.00000,1,[297],[0.],2.457333,26,7.0,7.0,7.0
55,Scn1a,0.00000,1,[975 973 970 947 903],[0. 0. 0. 0. 0.],2.386572,47,8.0,8.0,8.0
56,Nbas,0.00000,1,[1855 1895 1899 1854],[0. 0. 0. 0.],2.367992,38,7.0,7.0,7.0
57,Zswim4,0.00000,1,[216 221],[0. 0.],2.202616,14,5.0,5.0,5.0
58,1700012B07Rik,0.02787,0,[112],[0.],3.158133,16,8.0,8.0,8.0
59,Kif5b,0.02787,0,[156 165],[0. 0.],2.717943,9,5.0,5.0,5.0

In [9]:
mouse_pos_result

,Gene,Uniprot_ID,F,Pos,Mut_in_gene,Mut_in_res,Mut_in_vol,Obs_anomaly,Ratio_obs_sim,pval,...,Tot_samples,Samples_in_vol,Samples_in_comm_vol,Mut_in_comm_vol,Res_in_comm,pLDDT_res,pLDDT_vol,pLDDT_comm_vol,Cancer,Cohort
0,1520401A03Rik,A0A0J9YVH6,1,561,9,1,2,0.135332,0.943700,0.5018,...,9,2,NaN,NaN,NaN,31.62,33.105,NaN,Liver,Liver_strelka_2017
1,1520401A03Rik,A0A0J9YVH6,1,559,9,1,2,0.134568,0.995312,0.4354,...,9,2,NaN,NaN,NaN,34.59,33.105,NaN,Liver,Liver_strelka_2017
2,1520401A03Rik,A0A0J9YVH6,1,503,9,1,1,0.064167,0.509408,1.0000,...,9,1,NaN,NaN,NaN,33.93,33.930,NaN,Liver,Liver_strelka_2017
3,1520401A03Rik,A0A0J9YVH6,1,596,9,1,1,0.062337,0.527303,1.0000,...,9,1,NaN,NaN,NaN,48.94,48.940,NaN,Liver,Liver_strelka_2017
4,1520401A03Rik,A0A0J9YVH6,1,462,9,1,1,0.061768,0.577629,1.0000,...,9,1,NaN,NaN,NaN,38.65,38.650,NaN,Liver,Liver_strelka_2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117281,Zzz3,Q6KAQ7,1,611,18,1,1,0.023702,0.457698,1.0000,...,15,1,NaN,NaN,NaN,47.06,47.060,NaN,Liver,Liver_strelka_2017
117282,Zzz3,Q6KAQ7,1,605,18,1,1,0.023573,0.471635,1.0000,...,15,1,NaN,NaN,NaN,48.99,48.990,NaN,Liver,Liver_strelka_2017
117283,Zzz3,Q6KAQ7,1,220,18,1,1,0.022321,0.462874,1.0000,...,15,1,NaN,NaN,NaN,40.26,40.260,NaN,Liver,Liver_strelka_2017
117284,Zzz3,Q6KAQ7,1,509,18,1,1,0.020447,0.439525,1.0000,...,15,1,NaN,NaN,NaN,88.91,88.910,NaN,Liver,Liver_strelka_2017
117285,Zzz3,Q6KAQ7,1,705,18,1,1,0.020061,0.447043,1.0000,...,15,1,NaN,NaN,NaN,90.45,90.450,NaN,Liver,Liver_strelka_2017

# LiftOver from mm38 to mm39